name: conference_schedule
description: Flutter Global Summit Vol.2 conference schedule app
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  auto_route: 3.1.3
  cached_network_image: 3.2.0
  dartx: 1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: 8.0.0
  font_awesome_flutter: 9.2.0
  get_it: 7.2.0
  injectable: 1.5.0
  intl: 0.17.0
  json_annotation: 4.4.0
  url_launcher: 6.0.17

dev_dependencies:
  auto_route_generator: 3.1.0
  build_runner: 2.1.5
  flutter_lints: 1.0.4
  freezed: 1.0.2
  injectable_generator: 1.5.2
  json_serializable: 6.1.1

flutter:
  uses-material-design: true
